# This file is generated by tools/dump_mk.py
fn_mpfs=mpfshell --reset -n -c  ${1}
# mpfshell commands
mpy_mk_src_dirs:=md /mpy_env
mpy_put_src_files:=cd /mpy_env;lcd \"$(PWD)/mpy_env\";mput ^\w+\.py$$
mpy_rm_src:=cd /mpy_env;mrm ^\w+\.py$$;cd /mpy_env/..;rm /mpy_env
mpy_mk_tests_dirs:=md /tests
mpy_put_tests_files:=cd /tests;lcd \"$(PWD)/tests\";mput ^\w+\.py$$
mpy_rm_tests:=cd /tests;mrm ^\w+\.py$$;cd /tests/..;rm /tests
mpy_mk_examples_dirs:=
mpy_put_examples_files:=cd /.;lcd \"$(PWD)/examples\";mput ^\w+\.(py|json)$$
mpy_rm_examples:=cd /.;mrm ^\w+\.(py|json)$$
